version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - davegallant
    assignees:
      - davegallant
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - davegallant
    assignees:
      - davegallant
