version: "3.9"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 80:80
      - 443:443
    links:
      - "backend:backend"
    volumes:
      - ./data:/data
  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    ports:
      - 8080:8080
    env_file: .env
