services:
  frontend:
    image: ghcr.io/davegallant/rfd-fyi-frontend
    ports:
      - 80:80
      - 443:443
    links:
      - "backend:backend"
    volumes:
      - ./data:/data
    restart: always
  backend:
    image: ghcr.io/davegallant/rfd-fyi-backend
    ports:
      - 8080:8080
    restart: always
